### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by kuzichevapd** [pavelminin2002/Laba_3#6]
**class Cell:**
- enum class CellColor can be simplified 
var c не используется, ее можно убрать, и в принципе не добавлять в скобках цвета
- смысл переопределять equals и hashcode, если кажется конкретно сравнение cell нигде не происходит кроме тестов, 
а везде идет сравнение лишь их цветов

**class Chip:**
- есть ли смысл делать его open, т к (как я поняла) это для того, чтобы можно было его наследовать, но вроде он нигде не наследуется?

**class Board:**
- fun readyEat() можно сделать private и нужно ли ее выносить, если она использеутся лишь раз и ее функционал просто в возвращении
- нейминг bcng/wcng - не совсем понятно, что они делают, если смотришь первый раз
- нейминг goalbef 
- должны ли cells и turn быть публичными?
- заменить дублирование кода в местах, где идет проверка вокруг клетки
строки 202 - 206
строки 180 - 189
строки 166 - 170
например, с помощью вынесения функции -
`fun chooseDirection(i: Int): MutableList<Int> {
        val signs = mutableListOf<Int>()
        if ( i == 0 ) {
            signs.add(1)
            signs.add(1)
        }
        if ( i == 1 ) {
            signs.add(1)
            signs.add(-1)
        }
        if ( i == 2 ) {
            signs.add(-1)
            signs.add(1)
        }
        if ( i == 3 ) {
            signs.add(-1)
            signs.add(-1)
        }
        return signs
    }`
можно сделать по другому - примерный вариант
`for ( i in 0..3) {
                result = checkEat(Cell(cell.x + chooseDirection(i)[0], cell.y + chooseDirection(i)[1],
                    CellColor.BROWN), chooseDirection(i)[0], chooseDirection(i)[0], result)
            }`

**CheckersView**
Добавить кнопку для изменения позиции

**Comment by pavelminin2002** [comment]
все исправили. 
cells и turn должны быть публичными
